---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: Borealis
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora-dx
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  - type: script
    scripts:
      - "devpod.sh"
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/che/zed/repo/fedora-%OS_VERSION%/che-zed-fedora-%OS_VERSION%.repo
    install:
      - micro
      - starship
      - rust
      - cargo
      - zed
      - gparted

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      install:
        - app.drey.Warp
        - cc.arduino.IDE2
        - org.videolan.VLC
        - org.wireshark.Wireshark
        - re.sonny.Workbench
        - org.prismlauncher.PrismLauncher
        - org.libreoffice.LibreOffice
        - com.prusa3d.PrusaSlicer
        - com.obsproject.Studio
        - com.bitwig.BitwigStudio
        - org.kde.krita

    user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
